### ISSUE TITLE
Reset goals is not working

### ISSUE THREAD

**Issue by cdupuis** [atomist/sdm#355]
```
{"mapped_parameters":[{"name":"owner","value":"atomist"},{"name":"repo","value":"sample-sdm"},{"name":"providerId","value":"zjlmxjzwhurspem"}],"secrets":[{"uri":"github://user_token","value":"7**************************************0"}],"command":"ResetGoalsOnCommit","source":{"user_agent":"slack","slack":{"team":{"id":"T29E48P34","name":"atomist-community"},"channel":{"id":"CA668UD6F","name":"sample-sdm"},"user":{"id":"U29DXPR8R","name":"cd"},"thread_ts":null}},"correlation_id":"b3f32102-a990-4d62-bc4d-e3cb470b7b52","team":{"id":"T29E48P34","name":"atomist-community"},"automation":{"name":"@atomist/sample-sdm","version":"0.5.1"},"api_version":"1","parameters":[{"name":"sha","value":"3f1f944af19b607a908b88cfe4c19cacb30cc36f"}]}
```

results in

```
2018-05-02T04:19:27.946Z [w:15:2c2b1458-a20a-4472-b89e-63cc59156558:atomist-community:ResetGoalsOnCommit:154] [error] Failed invocation of command 'ResetGoalsOnCommit': {"name":"Error","message":"Repository not found: atomist/undefined","stack":"Error: Repository not found: atomist/undefined\n    at Object.<anonymous> (/app/node_modules/@atomist/sdm/handlers/commands/triggerGoal.js:110:19)\n    at Generator.next (<anonymous>)\n    at fulfilled (/app/node_modules/@atomist/sdm/handlers/commands/triggerGoal.js:28:58)\n    at propagateAslWrapper (/app/node_modules/async-listener/index.js:502:23)\n    at /app/node_modules/async-listener/glue.js:188:31\n    at /app/node_modules/async-listener/index.js:539:70\n    at /app/node_modules/async-listener/glue.js:188:31\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:182:7)"}
```

**Comment by cdupuis** [comment]
This is still or again not working.
