### ISSUE TITLE
SDM doesn't start with 1.0.0-M.1

### ISSUE THREAD

**Issue by cdupuis** [atomist/sdm#495]
Starting the SDM in a docker image (presumingly with NODE_ENV=production), it fails to start:

```
2018-08-28T19:57:02.693Z [m:1] [error] {"code":"MODULE_NOT_FOUND","name":"Error","message":"Cannot find module 'sprintf-js'","stack":"Error: Cannot find module 'sprintf-js'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:507:25)\n    at Module.require (internal/modules/cjs/loader.js:637:17)\n    at require (internal/modules/cjs/helpers.js:20:18)\n    at Object.<anonymous> (/app/node_modules/src/util/spawned.ts:24:1)\n    at Module._compile (internal/modules/cjs/loader.js:689:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)\n    at Module.load (internal/modules/cjs/loader.js:599:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:530:3)"}
```

Versions installed:

```
"@atomist/automation-client": "^1.0.0-M.2",
"@atomist/sdm": "^1.0.0-M.1",
"@atomist/sdm-core": "^1.0.0-M.1"
```

**Comment by cdupuis** [comment]
Fixed 
• automation-client-ts#7201b4d57c04599c886feccdb2d43580db519099
• atomist/sdm#10897cbb5a1d226263359e8de5ee42605b4d4cf3
• atomist/sdm-core#19bc8f86dd627edcd23107a8f1bd423bb612e70a
