### ISSUE TITLE
No such file or directory `~/.atomist.log`

### ISSUE THREAD

**Issue by snicoll** [atomist/sdm#514]
I've followed the [instructions to install a SDM](https://atomist.com/developer.html)

Whatever command I run next ends up with

```
{ errno: -2,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: '/Users/snicoll/.atomist/log',
  name: 'Error',
  message: 'ENOENT: no such file or directory, mkdir \'/Users/snicoll/.atomist/log\'',
  stack: 'Error: ENOENT: no such file or directory, mkdir \'/Users/snicoll/.atomist/log\'\n    at Object.fs.mkdirSync (fs.js:887:18)\n    at addFileTransport (/usr/local/lib/node_modules/@atomist/cli/node_modules/src/internal/util/logger.ts:23:12)\n    at initLogging (/usr/local/lib/node_modules/@atomist/cli/node_modules/src/internal/util/logger.ts:159:9)\n    at Object.<anonymous> (/usr/local/lib/node_modules/@atomist/cli/node_modules/src/internal/util/logger.ts:194:1)\n    at Module._compile (module.js:612:30)\n    at Object.Module._extensions..js (module.js:623:10)\n    at Module.load (module.js:531:32)\n    at tryModuleLoad (module.js:494:12)\n    at Function.Module._load (module.js:486:3)\n    at Module.require (module.js:556:17)' }
```

If I create `/Users/snicoll/.atomist/log` manually, the error goes away.

**Comment by cdupuis** [comment]
Urgh, that is bad. Thanks for reporting.

**Comment by cdupuis** [comment]
Related issue atomist/automation-client-ts#361 created

**Comment by cdupuis** [comment]
Related issue atomist/sdm-local#174 created

**Comment by cdupuis** [comment]
Fixed in automation-client.
