### ISSUE TITLE
Running atomist-internal-sdm against staging

### ISSUE THREAD

**Issue by slimslenderslacks** [atomist/sdm#567]
the `sdm-testing` namespace contains a copy of atomist-internal-sdm running against an atm-staging workspace:

```
Version 0.3.1-master.20181023193619  Sha 01b2d32  Repository git@github.com:atomist/atomist-internal-sdm.git
  Workspace AK748NQC5  Policy durable  Cluster enabled  Environment gke-int-production
  Commands 8  Events 8  Ingester 1
```

This uses the slack team:  https://atm-staging.slack.com/messages/CDU23TC1H/

Goals are getting planned by our push rules and our first autofix goal is going into READY and kicking off a kube job with the autofix goal.  The k8 jobs are not finishing:

```
(node:9) UnhandledPromiseRejectionWarning: Error: Network error: Unexpected token S in JSON at position 0
    at new ApolloError (/opt/app/node_modules/src/errors/ApolloError.ts:56:5)
    at /opt/app/node_modules/src/core/QueryManager.ts:519:31
    at /opt/app/node_modules/src/core/QueryManager.ts:1060:11
    at Array.forEach (<anonymous>)
    at /opt/app/node_modules/src/core/QueryManager.ts:1059:10
    at Map.forEach (<anonymous>)
    at QueryManager.broadcastQueries (/opt/app/node_modules/src/core/QueryManager.ts:1053:18)
    at /opt/app/node_modules/src/core/QueryManager.ts:418:18
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
    at emitWarning (internal/process/promises.js:48:15)
    at emitPromiseRejectionWarnings (internal/process/promises.js:103:9)
    at process._tickCallback (internal/process/next_tick.js:183:42)
(node:9) Error: Network error: Unexpected token S in JSON at position 0
    at new ApolloError (/opt/app/node_modules/src/errors/ApolloError.ts:56:5)
    at /opt/app/node_modules/src/core/QueryManager.ts:519:31
    at /opt/app/node_modules/src/core/QueryManager.ts:1060:11
    at Array.forEach (<anonymous>)
    at /opt/app/node_modules/src/core/QueryManager.ts:1059:10
    at Map.forEach (<anonymous>)
    at QueryManager.broadcastQueries (/opt/app/node_modules/src/core/QueryManager.ts:1053:18)
    at /opt/app/node_modules/src/core/QueryManager.ts:418:18
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
(node:9) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:78:13)
    at emitWarning (internal/process/promises.js:71:3)
    at emitPromiseRejectionWarnings (internal/process/promises.js:103:9)
    at process._tickCallback (internal/process/next_tick.js:183:42)

```

I suspect this is a configuration problem.  It's all in the `sdm-testing` namespace.

**Comment by cdupuis** [comment]
Issue moved to atomist/atomist-internal-sdm#25
