### ISSUE TITLE
Target `command` for `menuForCommand` needs an intent

### ISSUE THREAD

**Issue by slimslenderslacks** [atomist/sdm#633]
When creating a `SlackMessage` action:
```
menuForCommand(
                            {
                                text: "select fingerprint",
                                options: [
                                    ...fps.map(x => {
                                        return {
                                            value: x.name,
                                            text: x.name,
                                        };
                                    }),
                                ],
                            },
                            ListOneFingerprintTarget,
                            "fingerprint",
                            {},
                        ),
```

the target `ListOneFingerprintTarget` seems to require an `intent` to be set.  If I remove the `intent` from the taret CommandHandlerRegistration, then I get errors like:
```
2018-12-19T02:52:42.708Z [m:21297:92a4d703-6dc7-4108-ac75-22a9db766686:atm-slimslender:ListFingerprintTargets:735] [error] Error executing command 'ListFingerprintTargets': Unable to determine the name of this command. Please pass the name as a string or an instance of the command
2018-12-19T02:52:42.715Z [m:21297:92a4d703-6dc7-4108-ac75-22a9db766686:atm-slimslender:ListFingerprintTargets:742] [error] Error: Unable to determine the name of this command. Please pass the name as a string or an instance of the command
    at commandName (/Users/slim/atomist/atomist/sdm-pack-fingerprints/node_modules/@atomist/automation-client/lib/spi/message/MessageClient.ts:373:15)
    at Object.menuForCommand (/Users/slim/atomist/atomist/sdm-pack-fingerprints/node_modules/@atomist/automation-client/lib/spi/message/MessageClient.ts:334:17)
    at Object.<anonymous> (/Users/slim/atomist/atomist/sdm-pack-fingerprints/lib/handlers/commands/showTargets.ts:239:25)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/slim/atomist/atomist/sdm-pack-fingerprints/lib/handlers/commands/showTargets.js:28:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)

```

and if I add the intent back, everything works.  The `intent` is not technically required.

**Comment by cdupuis** [comment]
Tightened typings of `menuForCommand` so that calling the function with a `CommandHandlerRegistration` isn't possible any longer.

**Comment by cdupuis** [comment]
Also added `actionableMenu` to SDM with 9ddfe18181832c8b49a2443e190a4a6179d3966e
